ExoKomodo/Edu

- .github/workflows/client.yaml
- .github/workflows/server.yaml
> 45: Prevent duplicate workflow runs

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> 48: Add pull request template

- client/src/components/BlogLink.vue
- client/src/components/Instructors.vue
- client/src/index.css
- client/src/views/BlogView.vue
- client/src/views/HomeView.vue
Closes #35
If you want different styling feel free to send that info back, I'm generally happy with it. I also had to populate with dummy data - locally I am getting CORS errors for the blog page, so I haven't seen this with the current API data.
> updated styling for blogs page

- client/src/services/BlogService.ts
- server/Program.fs
- server/nginx/server.conf
> 52: Fix CORS for local development

- client/src/components/BlogPost.vue
- client/src/models/index.ts
- client/src/services/BlogService.ts
- client/src/views/BlogPostView.vue
- client/src/views/BlogView.vue
- server.tests/server.tests.fsproj
- server/Data/blogs/1.html
- server/Data/blogs/index.json
- server/Helpers.fs
- server/Models/Blog.fs
- server/Models/BlogIndex.fs
- server/Models/BlogMetadata.fs
- server/Routes/Blog.fs
- server/server.fsproj
> 59: Add git driven cms

- .do/app.yaml
- .github/workflows/server.yaml
> 61: Deploy DO app on push

- client/src/components/BlogLink.vue
Closes #55 
Reference: https://vuejs.org/guide/components/props.html#prop-passing-details
> 55: Use v-bind colon syntax for RouterLink

- server/server.fsproj
> 63: Include HTML files in Data/

- .github/CODEOWNERS
> 65: Add CODEOWNERS

- server.tests/Tests.fs
- server/Api/Index.fs
- server/Api/Routes.html
- server/Api/V1/Blog.fs
- server/Api/V1/Index.fs
- server/Api/V1/Ping.fs
- server/Api/V1/Routes.html
- server/Index.fs
- server/Program.fs
- server/Routes.html
- server/Routes/Index.fs
- server/server.fsproj
> 38: Add API instructions to root routes

- server/Api/V1/Blog.fs
- server/Models/Blog.fs
- server/Models/BlogIndex.fs
- server/Models/BlogMetadata.fs
- server/Models/Module.fs
- server/server.fsproj
> 70: Serialize blog types as XML

- .github/ISSUE_TEMPLATE/content.yml
> 75: Add issue template for issue category

- client/src/components/BlogPost.vue
- client/src/index.css
- client/src/views/AboutView.vue
- client/src/views/BlogView.vue
- client/src/views/HomeView.vue
- server/Data/blogs/2.html
- server/Data/blogs/index.json
Closes #99 
Tweaked the landing page a little for mobile, updated the about page as well. 
I am debating nixing either the Contact page, or the About page; we can just make one page out of these. Eventually we will make another page for video tutorials, and paid user login.
> 99 content beyond the basics article

- .vscode/extensions.json
- client/src/components/Navbar.vue
- client/src/views/BlogView.vue
- client/tailwind.config.js
> 40: Add issue creation button

- client/src/components/CourseLink.vue
- client/src/components/CoursePost.vue
- client/src/index.css
- client/src/models/index.ts
- client/src/router/index.ts
- client/src/services/BlogService.ts
- client/src/services/CourseService.ts
- client/src/services/HttpServiceV1.ts
- client/src/views/CoursePostView.vue
- client/src/views/CourseView.vue
- server.tests/README.md
- server.tests/Tests.fs
- server/Api/V1/Course.fs
- server/Api/V1/Routes.html
- server/Data/courses/index.json
- server/Data/courses/intro.html
- server/Models/Module.fs
- server/Program.fs
- server/server.fsproj
> 106: Replicate blog pages for courses

- .github/workflows/server.yaml
- client/src/models/index.ts
- client/src/views/CourseView.vue
- server/Api/V1/Blog.fs
- server/Api/V1/Course.fs
- server/Dockerfile
- server/Program.fs
- server/README.md
- server/server.fsproj
> 111: Add course database

- .do/app.yaml
> 111: Add MONGODB_URI to app spec

- .do/app.yaml
- client/package-lock.json
- client/package.json
- client/src/components/Navbar.vue
- client/src/components/__tests__/Navbar.spec.ts
- client/src/main.ts
- client/src/services/AuthService.ts
- client/src/services/BlogService.ts
- client/src/services/CourseService.ts
- client/src/services/HttpServiceV1.ts
- client/src/views/CoursePostView.vue
- client/src/views/CourseView.vue
- server.tests/Tests.fs
- server/Api/V1/Course.fs
- server/Helpers.fs
- server/Program.fs
- server/server.fsproj
Relates to #102 
Does not fully close it, as the `server` still needs to communicate with auth0
The `server` change will happen in a subsequent PR
> 102: Add login with Auth0

- client/src/index.css
- client/src/main.ts
- client/src/models/index.ts
- client/src/services/AuthService.ts
- client/src/services/HttpServiceV1.ts
- server.tests/Tests.fs
- server/Api/V1/Blog.fs
- server/Api/V1/Course.fs
- server/Api/V1/User.fs
- server/Constants.fs
- server/Data/courses/index.json
- server/Data/courses/intro.html
- server/Helpers.fs
- server/Models/Module.fs
- server/Program.fs
- server/server.fsproj
> 117: Create pseudo paid tier

- client/src/components/CoursePost.vue
- client/src/components/Navbar.vue
- client/src/components/Spinner.vue
- client/src/components/__tests__/Navbar.spec.ts
- client/src/router/index.ts
- client/src/services/AuthService.ts
- client/src/services/BlogService.ts
- client/src/services/CourseService.ts
- client/src/views/BlogPostView.vue
- client/src/views/BlogView.vue
- client/src/views/CoursePostView.vue
- client/src/views/CourseView.vue
> 125: Add loading spinner

- client/package-lock.json
- client/package.json
- client/src/components/CourseEditor.vue
- client/src/components/CoursePost.vue
- client/src/main.ts
- client/src/services/AuthService.ts
- client/src/services/BlobService.ts
- client/src/services/BlogService.ts
- client/src/services/CourseService.ts
- client/src/services/HttpServiceV1.ts
- client/src/views/BlogPostView.vue
- client/src/views/BlogView.vue
- client/src/views/CoursePostView.vue
- client/src/views/CourseView.vue
- server/Program.fs
> 127: Add toast notification

- client/src/components/Button.vue
- client/src/components/Navbar.vue
> 133: Remove bug button

- server/Dockerfile
> PATCH: Add apt-transport-https

- exokomodo.lib/Auth0/Module.fs
- exokomodo.lib/Giraffe/Handlers.fs
- exokomodo.lib/Serializers/Json.fs
- exokomodo.lib/Serializers/Module.fs
- exokomodo.lib/exokomodo.lib.fsproj
- server.tests/TestApi.fs
- server/Api/V1/User.fs
- server/Handlers.fs
- server/Program.fs
> 147: Add other auth providers

- .config/dotnet-tools.json
- .editorconfig
- server.tests/Index/Api/Tests.fs
- server.tests/Index/Api/V1/Assignment/Tests.fs
- server.tests/Index/Api/V1/Blob/Tests.fs
- server.tests/Index/Api/V1/Blog/Tests.fs
- server.tests/Index/Api/V1/Course/Tests.fs
- server.tests/Index/Api/V1/Section/Tests.fs
- server.tests/Index/Api/V1/Tests.fs
- server.tests/Index/Tests.fs
- server.tests/TestApi.fs
- server/Api/V1/Blob.fs
- server/Api/V1/Blog.fs
- server/Api/V1/Builder.fs
- server/Api/V1/User.fs
- server/Constants.fs
- server/Handlers.fs
- server/Models/Module.fs
- server/Program.fs
> Add formatter rules

- server/src/Models/Module.fs
> Fix section update

- client/src/components/Button.vue
> replace a tag with button tag for hover consistency

- .github/workflows/client.yaml
- .github/workflows/server.yaml
Closes #<insert issue number here>
> Set up workflow_dispatch

- .github/workflows/client.yaml
- .github/workflows/server.yaml
Closes #<insert issue number here>
> Fix up paths for trigger

- .github/workflows/client.yaml
- .github/workflows/server.yaml
Closes #<insert issue number here>
> Artifact workflow

- client/src/views/HomeView.vue
Closes #<insert issue number here>
> Remove period

- client/src/views/HomeView.vue
Set copyright year with JS Date object, on visit
> 181: Set copyright year programmatically
